# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BuscaOficinas' do
  use_frameworks!
  pod 'Alamofire'
  pod 'AlamofireObjectMapper'
  pod 'Nuke'

  # Pods for BuscaOficinas

  target 'BuscaOficinasTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BuscaOficinasUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
